FROM node:20-alpine

WORKDIR /frontend

COPY package.json .
COPY package-lock.json .

RUN npm install

COPY . .

EXPOSE 3000

CMD [ "npm", "run", "dev" ]

# CMD ["sh", "-c", "while :; do sleep 1; done"]